[[Clingo]]
arch = "aarch64"
git-tree-sha1 = "a5f5b166437ef1ce8f8c28222390b0d5cf3c4b01"
os = "macos"

    [[Clingo.download]]
    sha256 = "f60e0c208fcb3696023d99a211d19825f8b63018563307e20c3fb57f348b86ba"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.aarch64-apple-darwin.tar.gz"
[[Clingo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23e407584d18fc61010fd46c49f64aec6810c693"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "acb6241b082b04c95b5e3292ffcc9feae072458434a0493182b08822209102bd"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ec9de1db4c904a4921ed27855080048744657df"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "68c62569362783c3fd1c9d84236fe35c0f8e0b763bbf30a32dc34e8fc5d24050"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clingo]]
arch = "aarch64"
git-tree-sha1 = "e3b1154f32174ea89f878a1042e672b1eadfd695"
os = "freebsd"

    [[Clingo.download]]
    sha256 = "42d62b6f672548ab8ca4be63e6f8eb566775dc7111c94ccd25ce2d630d9522c4"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.aarch64-unknown-freebsd.tar.gz"
[[Clingo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d0e0440554e9321dfcaf56802172c264136f1ea"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "0e51a15a7b4d8961b59b4f58f79164e235e1283935d4a61bbb498a94a23912f8"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clingo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d9a4f217da5386a25afe2da821df54ea206cea6"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "efc1623f6fd34af2923fb040466624b9a452db8bd9de20ac4c3788b791fe74c1"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clingo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a800de93812d67ded758d873b4fea94a161fc25e"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "35889723d0c0385d796a4c02699f742dfd0f2b3b3c75923d490a9a60518f2b6c"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clingo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a86cc127a03b5b0825b24faf4e899eeb8650e4b4"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "d20e71d64fde4a8bcac218234cdeffdd0288b012e2067d8900338ff300cabbdb"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec7f62d0e5373b205a1a7f59b167a1db0646bf4e"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "528a70c06211386852413d49956bab5404b44492e0ea5e8961dc94b2afe9c04e"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.i686-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "668ddb4efa502c04fec93a15ea27f8f69cb17f9d"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "c0d50d05481f87d9f61b818e032c899d74a5597d0341e43607950ae1a1a88e1c"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.i686-linux-musl-cxx11.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb09efe143bb9829106434996497cfaa33e8656b"
os = "windows"

    [[Clingo.download]]
    sha256 = "58a6b5623cc7eb0def2fa55723837319a6a8d581103d9e762b307bb4408d6b00"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clingo]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a69136a28efbdb9cd8381871e9fad614a8d1a0c"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "adc4db32bd1a80a892df6e7b12fc9a899c11b56482bf1067978160486699da47"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a7d9f3e31674b4b1f62e2fd8acd53cc6c466873"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "9dd392e131bfdffac91310c8a0f4064d6b567dace3b37bad64844a4d46ae3ca3"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.riscv64-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "x86_64"
git-tree-sha1 = "d350f3e4fedcb30cd9c9d6da84f18e1e34735299"
os = "macos"

    [[Clingo.download]]
    sha256 = "6a4de50a3ab84a5e89b20da8309bc94d7f0692c2881f879f33dd99f795c8f57f"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.x86_64-apple-darwin.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9dca1c36d0329772b62e2d429ec1be720aa85c3"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "5f08c20a4ed484e0cac3480d6aa6de174e479e0b46dcb15edd44e7b0a8632d8e"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6493dfd10237410d71dc83e20c839cf51e1e55d1"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "b77ac2d57dde0825e475eafae6d92e2b7492ad868f060f32fc462c155744112d"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clingo]]
arch = "x86_64"
git-tree-sha1 = "52fd0fceb7a75bdc00d3bbfe477d997f4c9fb364"
os = "freebsd"

    [[Clingo.download]]
    sha256 = "da7ea27736d673ea1fa8850efaff2ced3c6686638eaa631f8438eab6669ae02d"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.x86_64-unknown-freebsd.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d855585daeca7c69e0aea98f4bb143ee984fe804"
os = "windows"

    [[Clingo.download]]
    sha256 = "69c8a6f7c3ad1c82f82e95b30f16d2dac6fc056924b622d7ed555aa72d2b7952"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.0+0/Clingo.v5.8.0.x86_64-w64-mingw32-cxx11.tar.gz"
