[[Clingo]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a286f348f9bc590a100be6a36caa05fba893c62"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "4a6e5f969b1873304b13acff7c569b499737fe083d59077128ddf1f3053760d7"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clingo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bf74a7fe2a46aa1e8a895658033f73be5c05930"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "3b3d78e585c50f73c4dc1479808d88e641f550d1a2f01d6e1cf6fe06e07c96b0"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2591d8974b783a86a290b1727f02d0bac6686193"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "f62cf0beb4661bef4633327c2f0b26ef9563e7d786ac297fe382d8fad25ea8bb"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clingo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3474cb5ee7d35f679e72ba91eba4f430ef153256"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "6d165291cba8e3d160055201a9d7309f980cc74b528187905c969f9fd9268bae"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clingo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34f9381d861b06e7f1d9968462e2229d0a3e1163"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "fa26595795ed28d028fd2f4518bc9c87c8b628de48b759644e2631c7041879ee"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clingo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4e98bcee43ec6c109208a859b30a6d9e7e3cec1"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "11eb2ed09740fb7c46de032330559e9283ee5a48c6ae5063a907c65278e94cc2"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clingo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d06ee75c602da6c38bd0fa6434333b4ec111908"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "b125ef40e1753937fc59a80efdd0f18d50deb1a8b82442cf2fc5a5d5723188d9"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clingo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b44fa7aeb5f3a5b09fb4ce83c71aa64486670966"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "6e14d3a0fc80a7d9e6c79e8b7c86366355580c010100eb2587ee4cbc64f95dec"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fb4f57095a502e4ea698e4e848c16167d6ae097"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "14420b6aeaf82a7baa6a078e8f31655bda19e0f190e432c3d2ad0d531b83e55f"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.i686-linux-gnu-cxx03.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3adbe7064c40e37f0b04272e117c19cde462de6b"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "48269b528a05423cba59c068ffe67d760867b061f37b62c8bd97170d7accbd58"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.i686-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d6ae5c30af6a7ef5057835a3fe13945c62ee870"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "1f807327775fc8f9cde2312c8fa1bd45f62fd457b5b2b3ea94cc4385ef3be33b"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.i686-linux-musl-cxx03.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03f46d042cedf8a91c6697238562b85673212042"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "b770a48c17077e4c00249b0280e8068fd64d0f2eee68757c2f81f9c1e5c32e93"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.i686-linux-musl-cxx11.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bea2e6f3d6c7f9ff4319e4c6fb58e0c17072e04"
os = "windows"

    [[Clingo.download]]
    sha256 = "836a0c3faad4ea2af3464210b701678e4d5869c9dbf8eb21992762a04f71a48f"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42f3d38e306257fcc79bc6099e87462f6846d662"
os = "windows"

    [[Clingo.download]]
    sha256 = "601fc514ea2a6e2b490cc0bcf9d4fe03eb444d8c9498b3601a03fc13888b293a"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clingo]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7345c730e7b50bb57f5af5dcaf2c7f4d31c9d8a1"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "0284c72ece748a7b32f86f81ba7a8fd73a5f5c172611227ae0cc2ba279f5a762"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clingo]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c485dfcd3d978bb248280f95633c65e3a07c3c11"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "14460342cf26c9a07ef9c3d4f7073116780fa94dd1b1901ea0d2af683b3682df"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "x86_64"
git-tree-sha1 = "9ee1674fa4b28f6bed36ed59783e430a483b8f6e"
os = "macos"

    [[Clingo.download]]
    sha256 = "f96125119f94865f7a59da290ff417413a257c667dfdd0a1d33ed3a15fef2dcc"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.x86_64-apple-darwin.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "568050fb266310c9a104a3dca10e90b542ca5e2e"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "78ed53c7090365518baf7474160749da13281f7adee3037b28ddf22e7a9845ef"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8db048f74bab717f47c45524077075cbacef549"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "e80c4b248b5612610de0e558005a1cc2616cea5275b4e3ca2170d7c7aa44133e"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2117b5ae690fd692c8d6567e1099d48d1d7f8b9e"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "ed778078811cba83d68f740b7695cd642ffbc8658359cffa778d6a80c5265418"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ce91b7dac63dcc64a9c5d44905951d0de59e290"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "efc07db3ce8a4123fa6a26aaa701df736c0d4689669ef069a92ecda19d0532bc"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clingo]]
arch = "x86_64"
git-tree-sha1 = "46cb53c329148f3c9beaa26593bb5baf427cf88e"
os = "freebsd"

    [[Clingo.download]]
    sha256 = "16cb41b6d9bc8e764d2b46da0e09a1930a79e04220a03cd626d26bf5844bbc92"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.x86_64-unknown-freebsd.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1aef6dcf9b823c87f2e22d869d9807f9c5c882e"
os = "windows"

    [[Clingo.download]]
    sha256 = "2f28bc328a5028ea25d0d13e6b1f8073558089cf8b6de495b461b23d69f9427c"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10e4940fa0d80feab72e810bcc2bd0aceabcf80f"
os = "windows"

    [[Clingo.download]]
    sha256 = "0e4ba272eee4045a08de5d87b1a1adee104925a6f029898313b70d38e2843d44"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.5.0+0/Clingo.v5.5.0.x86_64-w64-mingw32-cxx11.tar.gz"
