[[Clingo]]
arch = "aarch64"
git-tree-sha1 = "e39013a55db4a726c688927813aaf516fa48894a"
os = "macos"

    [[Clingo.download]]
    sha256 = "c395f214ea7fcb36418902880cee99b26bfa234d4ef6a648349f612e9795ec19"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.aarch64-apple-darwin.tar.gz"
[[Clingo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69fcc0534f98076d2eae647d1cd803bf9c625c55"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "4b84b3cd3c1d6822450050dda85b39e72ed68e7f11598210c87b2cd3e9ccfcc6"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "634ffc125c068e1fe0538718b3c93dfb874c1a56"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "d12368577064a8fcd2ae0e6254b35c7c4a57261f5cdff2cfa80219ae2b348af3"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.aarch64-linux-musl-cxx11.tar.gz"
[[Clingo]]
arch = "aarch64"
git-tree-sha1 = "49a2aff7e8f1424769dc4d8bd800a656042e1620"
os = "freebsd"

    [[Clingo.download]]
    sha256 = "1b6116a61574d4e1bb92226e3d559326456034fc7a8154c382fa8b61b12a71e1"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.aarch64-unknown-freebsd.tar.gz"
[[Clingo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef344203fe2f27bf59adfa4ff96d9978f31a8b85"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "3d4a70ee1c306be4fe2901b2ab4bf8cac2ada2e5b04cfd1d18ee703c4d19bf19"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clingo]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a91a6cec9e58187967d514333d3b97f98726ef4d"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "6cce95c8c02c3e2e8555c6b3325676c902ca706b6074b88e08e5be3043610dca"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clingo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd655ce26f3a89d40d59c15b7dec2bb1c93490d3"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "f6abaee90262e83c01fbf6353402e089932df8a71a056c9da8ebe116e959842b"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clingo]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4c7c6ba63eff13acd56e3fa0599d2f306c1a4e3"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "893c2dfcb3a5b9780314fb5dec9dbab3048cf80f1162adefe56b337c7cc15b8a"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "208088334966dbfa1c0b77abdae92e778f4d6d26"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "57f1cde44ada4b8bcdfe19f655a839a4dde860985bc445a44fb34e273dceda29"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.i686-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4898ad49a730ffefe1ae87ccb26282bac349f437"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "8f3f92bcd67758c1e0a0c9ac31df3e3ba4c358aaaa430c6934d725bf61e0083e"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.i686-linux-musl-cxx11.tar.gz"
[[Clingo]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03bbbc8a1ade3334dfd288f8d9b44f334cbd1f55"
os = "windows"

    [[Clingo.download]]
    sha256 = "236a878f742e4519319a73b6f54e71a55cb6edd51f5efa569ad0dfb9771c60b6"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.i686-w64-mingw32-cxx11.tar.gz"
[[Clingo]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "033c5ee6fd7992447622d04859fa47d7b9be903b"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "bed605c622c421228f812062a24c9bdeddad2912668acdc288cdb846c546b885"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a749af49440f423cf5ca695b72d0cb4524bb7d8"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "68de0164409ba549e5ef3b4e0d02085135c193709376dfdd91e979626d88784e"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.riscv64-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "x86_64"
git-tree-sha1 = "47666c2f033290160baa4f4b526218cc4e7b44ef"
os = "macos"

    [[Clingo.download]]
    sha256 = "3c86790ba61c6c3c30afecfc2b49dcac36b2f61a2b76f83cb23b455a20e06e02"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.x86_64-apple-darwin.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b608a1cb1d9078f77e14ff7653cf103c7c344610"
libc = "glibc"
os = "linux"

    [[Clingo.download]]
    sha256 = "105f949a4ad3640ffc78c9801a4ea5a48249abf4ec484109d8f854887003c3be"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "789e009190d51ea337e3c65c500f235fc1285f10"
libc = "musl"
os = "linux"

    [[Clingo.download]]
    sha256 = "7eb94e691c15a7f413786e2487f05cab3cac1b4498652196c0d2d1393383e4f6"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.x86_64-linux-musl-cxx11.tar.gz"
[[Clingo]]
arch = "x86_64"
git-tree-sha1 = "9ce8e51bee9a516f0f6428e0e1bea1fb5f8156ca"
os = "freebsd"

    [[Clingo.download]]
    sha256 = "80fbcd519252dd5ee565ff71359d29eef9dbe49ef4c5107fd86c8374cd9d9d79"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.x86_64-unknown-freebsd.tar.gz"
[[Clingo]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0c05c09900dcc0dcfcc8079bd9ab08fd72ecb30"
os = "windows"

    [[Clingo.download]]
    sha256 = "f0d0abeb338d24a7c035ecd0a1d50b0af659593d2cf6823e862762b396b25e0e"
    url = "https://github.com/JuliaBinaryWrappers/Clingo_jll.jl/releases/download/Clingo-v5.8.2+0/Clingo.v5.8.2.x86_64-w64-mingw32-cxx11.tar.gz"
